default:
  tags:
    - runner:main

gitlab_autoinstrumentation_test:
  image: adoptopenjdk/openjdk11:latest
  script:
    - eval $(LANGUAGES="java" API_KEY="dummy" bash <(cat script.sh))
    - export LOG_FILE=java-output.log
    - export TRACER_INIT_LOG="CI Visibility settings"
    - java -version 2>&1 | tee $LOG_FILE
    - | 
      grep -q "$TRACER_INIT_LOG" $LOG_FILE || { echo "Error: Output does not contain tracer initialisation log: $TRACER_INIT_LOG"; exit 1; }

